In [1]:
import numpy as np

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
print(data)

[[ 1  6 15 88 20]
 [ 6 71 30 79 19]
 [67 34 47 39 43]
 [41 53 76 66 85]
 [59 54 85 47 35]]


In [11]:
data[1], data[3] = data[3].copy(), data[1].copy()
data

array([[67, 34, 47, 39, 43],
       [41, 53, 76, 66, 85],
       [59, 54, 85, 47, 35],
       [ 1,  6, 15, 88, 20],
       [ 6, 71, 30, 79, 19]])

In [24]:
data1 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data1
min_val = data1.min()
max_val = data1.max()
normalized_data = (data1 - min_val) / (max_val - min_val)
normalized_data

array([[0.93617021, 0.96808511, 0.92553191, 0.73404255, 0.04255319],
       [0.90425532, 0.06382979, 0.17021277, 0.75531915, 1.        ],
       [0.78723404, 0.37234043, 0.        , 0.89361702, 0.5212766 ],
       [0.45744681, 0.20212766, 0.37234043, 0.88297872, 0.95744681],
       [0.87234043, 0.38297872, 0.38297872, 0.91489362, 0.44680851]])

In [25]:
data2 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data2
mean = np.mean(data2)
std = np.std(data2)
z_score_data = (data2 - mean) / std
z_score_data

array([[-1.49236514,  0.93167428,  1.38837736, -1.56262715,  1.35324635],
       [ 0.08853014, -0.1222559 ,  1.17759132,  1.31811535,  0.96680529],
       [-0.86000703,  0.33444718, -0.33304194,  0.05339913, -0.86000703],
       [-0.82487602, -1.52749614, -0.29791093, -0.36817294,  0.79115026],
       [-1.87880621, -0.40330395,  0.89654328, -0.01686288,  1.24785334]])

In [26]:
data3 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data3
vector_data = np.ravel(data3)
sub_arrays = np.split(vector_data, 5)
for sub_array in sub_arrays:
    print(sub_array)

[80 82  9  4 65]
[57  7 18 92 63]
[70 72 53  2 91]
[86 22 93 90 20]
[76 16 54 68 76]


In [17]:
vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])
dot_product = np.dot(vector1, vector2)
dot_product

198

In [27]:
data4 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data5 = np.array([[2, 4, 6],
                  [1, 3, 5],
                  [3, 5, 7]])
result = np.dot(data4[:3, :3], data5)
result

array([[368, 668, 968],
       [258, 542, 826],
       [375, 669, 963]])

In [19]:
identity_matrix = np.identity(3)
scaled_matrix = identity_matrix * 2
inverse_matrix = np.linalg.inv(scaled_matrix)
inverse_matrix

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [28]:
data6 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
sub_matrix = data6[:3, :3]
eigenvalues, eigenvectors = np.linalg.eig(sub_matrix)
eigenvalues
eigenvectors

array([[-0.60691948, -0.89688874,  0.12207625],
       [-0.3844173 ,  0.42244681, -0.80306904],
       [-0.69560915,  0.1308789 ,  0.58324738]])

In [29]:
data7 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data7

array([[55, 38, 88,  9, 58],
       [57, 27, 28, 27, 18],
       [65, 83, 68, 15, 98],
       [22, 28, 31, 71, 83],
       [ 9, 78, 18, 86, 20]])

In [30]:
num_missing = 5
missing_indices = np.random.choice(data7.size, num_missing, replace=False)
data7.ravel()[missing_indices] = np.nan
data7

ValueError: cannot convert float NaN to integer

### 9 exercise dont understand

In [31]:
data8 = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data8


array([[88, 11, 31, 60, 73],
       [84, 18, 66, 15, 50],
       [40, 77,  6, 92, 50],
       [56, 86, 59, 97, 67],
       [ 8, 49, 69, 34, 92]])

In [32]:
num_missing = 5
missing_indices = np.random.choice(data.size, num_missing, replace=False)
data8.ravel()[missing_indices] = np.nan
data8

ValueError: cannot convert float NaN to integer