In [1]:
import numpy as np

In [2]:
vector_zero = np.zeros(10, dtype=float)

In [3]:
vector_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
vector_zero.itemsize

8

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
vector = np.arange(10,50)

In [12]:
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [28]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
matrix = np.arange(0,9)

In [26]:
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
no_zero_vector = np.nonzero([1, 2, 0, 0, 4, 0])

In [30]:
no_zero_vector

(array([0, 1, 4], dtype=int64),)

In [31]:
matrix_identity = np.eye(3, dtype=int)

In [32]:
matrix_identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
x = np.zeros((5,5))

In [38]:
x += np.arange(5)

In [39]:
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [13]:
vector_size_10 = np.linspace(0,1,12,endpoint=True)[1:-1]

In [14]:
vector_size_10

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [15]:
vector_random_10 = np.sort(np.random.rand(10))

In [16]:
vector_random_10

array([0.03400853, 0.17250395, 0.35561323, 0.43843179, 0.44201244,
       0.57205551, 0.61380911, 0.6383435 , 0.77052241, 0.89926896])

In [31]:
int8 = np.iinfo(np.int8)
int32 = np.iinfo(np.int32)
int64 = np.iinfo(np.int64)
float32 = np.finfo(np.float32)
float64 = np.finfo(np.float64)
int8.min


-128

In [32]:
int8.max

127

In [33]:
int32.min

-2147483648

In [34]:
int32.max

2147483647

In [35]:
int64.min

-9223372036854775808

In [36]:
int64.max

9223372036854775807

In [37]:
float32.min

-3.4028235e+38

In [38]:
float32.max

3.4028235e+38

In [39]:
float32.min

-3.4028235e+38

In [40]:
float64.max

1.7976931348623157e+308

In [45]:
float_array = np.array([1.5, 2.7, -3.2, 4.9], dtype=np.float32)

In [46]:
float_array

array([ 1.5,  2.7, -3.2,  4.9], dtype=float32)

In [47]:
float_array[:] = np.trunc(float_array).astype(np.int32)

In [48]:
float_array

array([ 1.,  2., -3.,  4.], dtype=float32)

In [49]:
vector_mean = np.arange(9).reshape(3, 3)

In [50]:
vector_mean = np.mean(vector_mean, axis=1)

In [51]:
vector_mean

array([1., 4., 7.])

In [52]:
vector_2D = np.random.randint(0, 10, (2, 3))

In [54]:
vector_2D = np.argsort(vector_2D, axis=0)

In [55]:
vector_2D

array([[0, 1, 0],
       [1, 0, 1]], dtype=int64)

In [58]:
arr = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
arr[[0,2]] = arr[[2,0]]
arr

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])

In [62]:
arr_new = np.array([0, 2, 0, 3, 1, 0, 0, 2])
arr2_new = np.repeat(np.arange(len(C)), C)
np.bincount(arr2_new)

array([0, 2, 0, 3, 1, 0, 0, 2], dtype=int64)

In [60]:
vector_bitcount

array([2, 3, 1], dtype=int64)